package com.zzz.entity;

public class Resumes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.did
     *
     * @mbg.generated
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.userNumber
     *
     * @mbg.generated
     */
    private String usernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.self_info
     *
     * @mbg.generated
     */
    private String selfInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.student_info
     *
     * @mbg.generated
     */
    private String studentInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.language_use
     *
     * @mbg.generated
     */
    private String languageUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.experience
     *
     * @mbg.generated
     */
    private String experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.speciality
     *
     * @mbg.generated
     */
    private String speciality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resumes.statc
     *
     * @mbg.generated
     */
    private Integer statc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.Id
     *
     * @return the value of resumes.Id
     *
     * @mbg.generated
     */
    
    public Integer getId() {
        return id;
    }

    public Resumes() {
		super();
		// TODO Auto-generated constructor stub
	}

    
	public Resumes(String name, Integer age, Integer sex, String usernumber, String selfInfo, String phone,
			String studentInfo, String major, String school, String languageUse, String experience, String speciality) {
		super();
		this.name = name;
		this.age = age;
		this.sex = sex;
		this.usernumber = usernumber;
		this.selfInfo = selfInfo;
		this.phone = phone;
		this.studentInfo = studentInfo;
		this.major = major;
		this.school = school;
		this.languageUse = languageUse;
		this.experience = experience;
		this.speciality = speciality;
		this.statc = 0;
	}
	
	public Resumes(String uid, Integer cid, Integer did, String name, Integer age, Integer sex, String usernumber,
			String selfInfo, String phone, String studentInfo, String major, String school, String languageUse,
			String experience, String speciality, Integer statc) {
		super();
		this.uid = uid;
		this.cid = cid;
		this.did = did;
		this.name = name;
		this.age = age;
		this.sex = sex;
		this.usernumber = usernumber;
		this.selfInfo = selfInfo;
		this.phone = phone;
		this.studentInfo = studentInfo;
		this.major = major;
		this.school = school;
		this.languageUse = languageUse;
		this.experience = experience;
		this.speciality = speciality;
		this.statc = statc;
	}

	
	public Resumes(Integer id, String uid, Integer cid, Integer did, String name, Integer age, Integer sex,
			String usernumber, String selfInfo, String phone, String studentInfo, String major, String school,
			String languageUse, String experience, String speciality, Integer statc) {
		super();
		this.id = id;
		this.uid = uid;
		this.cid = cid;
		this.did = did;
		this.name = name;
		this.age = age;
		this.sex = sex;
		this.usernumber = usernumber;
		this.selfInfo = selfInfo;
		this.phone = phone;
		this.studentInfo = studentInfo;
		this.major = major;
		this.school = school;
		this.languageUse = languageUse;
		this.experience = experience;
		this.speciality = speciality;
		this.statc = statc;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.Id
     *
     * @param id the value for resumes.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.uid
     *
     * @return the value of resumes.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.uid
     *
     * @param uid the value for resumes.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.cid
     *
     * @return the value of resumes.cid
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.cid
     *
     * @param cid the value for resumes.cid
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.did
     *
     * @return the value of resumes.did
     *
     * @mbg.generated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.did
     *
     * @param did the value for resumes.did
     *
     * @mbg.generated
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.name
     *
     * @return the value of resumes.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.name
     *
     * @param name the value for resumes.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.age
     *
     * @return the value of resumes.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.age
     *
     * @param age the value for resumes.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.sex
     *
     * @return the value of resumes.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.sex
     *
     * @param sex the value for resumes.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.userNumber
     *
     * @return the value of resumes.userNumber
     *
     * @mbg.generated
     */
    public String getUsernumber() {
        return usernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.userNumber
     *
     * @param usernumber the value for resumes.userNumber
     *
     * @mbg.generated
     */
    public void setUsernumber(String usernumber) {
        this.usernumber = usernumber == null ? null : usernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.self_info
     *
     * @return the value of resumes.self_info
     *
     * @mbg.generated
     */
    public String getSelfInfo() {
        return selfInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.self_info
     *
     * @param selfInfo the value for resumes.self_info
     *
     * @mbg.generated
     */
    public void setSelfInfo(String selfInfo) {
        this.selfInfo = selfInfo == null ? null : selfInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.phone
     *
     * @return the value of resumes.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.phone
     *
     * @param phone the value for resumes.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.student_info
     *
     * @return the value of resumes.student_info
     *
     * @mbg.generated
     */
    public String getStudentInfo() {
        return studentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.student_info
     *
     * @param studentInfo the value for resumes.student_info
     *
     * @mbg.generated
     */
    public void setStudentInfo(String studentInfo) {
        this.studentInfo = studentInfo == null ? null : studentInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.major
     *
     * @return the value of resumes.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.major
     *
     * @param major the value for resumes.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.school
     *
     * @return the value of resumes.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.school
     *
     * @param school the value for resumes.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.language_use
     *
     * @return the value of resumes.language_use
     *
     * @mbg.generated
     */
    public String getLanguageUse() {
        return languageUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.language_use
     *
     * @param languageUse the value for resumes.language_use
     *
     * @mbg.generated
     */
    public void setLanguageUse(String languageUse) {
        this.languageUse = languageUse == null ? null : languageUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.experience
     *
     * @return the value of resumes.experience
     *
     * @mbg.generated
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.experience
     *
     * @param experience the value for resumes.experience
     *
     * @mbg.generated
     */
    public void setExperience(String experience) {
        this.experience = experience == null ? null : experience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.speciality
     *
     * @return the value of resumes.speciality
     *
     * @mbg.generated
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.speciality
     *
     * @param speciality the value for resumes.speciality
     *
     * @mbg.generated
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality == null ? null : speciality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resumes.statc
     *
     * @return the value of resumes.statc
     *
     * @mbg.generated
     */
    public Integer getStatc() {
        return statc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resumes.statc
     *
     * @param statc the value for resumes.statc
     *
     * @mbg.generated
     */
    public void setStatc() {
        this.statc = 0;
    }

	@Override
	public String toString() {
		return "Resumes [id=" + id + ", uid=" + uid + ", cid=" + cid + ", did=" + did + ", name=" + name + ", age="
				+ age + ", sex=" + sex + ", usernumber=" + usernumber + ", selfInfo=" + selfInfo + ", phone=" + phone
				+ ", studentInfo=" + studentInfo + ", major=" + major + ", school=" + school + ", languageUse="
				+ languageUse + ", experience=" + experience + ", speciality=" + speciality + ", statc=" + statc + "]";
	}
    
}