package com.zzz.entity;

public class Role {
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column roles.Id
    *
    * @mbg.generated
    */
   private Integer id;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column roles.available
    *
    * @mbg.generated
    */
   private Boolean available;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column roles.name
    *
    * @mbg.generated
    */
   private String name;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column roles.description
    *
    * @mbg.generated
    */
   private String description;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column roles.Id
    *
    * @return the value of roles.Id
    *
    * @mbg.generated
    */
   public Integer getId() {
       return id;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column roles.Id
    *
    * @param id the value for roles.Id
    *
    * @mbg.generated
    */
   public void setId(Integer id) {
       this.id = id;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column roles.available
    *
    * @return the value of roles.available
    *
    * @mbg.generated
    */
   public Boolean getAvailable() {
       return available;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column roles.available
    *
    * @param available the value for roles.available
    *
    * @mbg.generated
    */
   public void setAvailable(Boolean available) {
       this.available = available;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column roles.name
    *
    * @return the value of roles.name
    *
    * @mbg.generated
    */
   public String getName() {
       return name;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column roles.name
    *
    * @param name the value for roles.name
    *
    * @mbg.generated
    */
   public void setName(String name) {
       this.name = name == null ? null : name.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column roles.description
    *
    * @return the value of roles.description
    *
    * @mbg.generated
    */
   public String getDescription() {
       return description;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column roles.description
    *
    * @param description the value for roles.description
    *
    * @mbg.generated
    */
   public void setDescription(String description) {
       this.description = description == null ? null : description.trim();
   }
}
