package com.zzz.entity;

public class UserRole {
	 /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column user_role.uid
    *
    * @mbg.generated
    */
   private Integer uid;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column user_role.rid
    *
    * @mbg.generated
    */
   private Integer rid;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column user_role.uid
    *
    * @return the value of user_role.uid
    *
    * @mbg.generated
    */
   public Integer getUid() {
       return uid;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column user_role.uid
    *
    * @param uid the value for user_role.uid
    *
    * @mbg.generated
    */
   public void setUid(Integer uid) {
       this.uid = uid;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column user_role.rid
    *
    * @return the value of user_role.rid
    *
    * @mbg.generated
    */
   public Integer getRid() {
       return rid;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column user_role.rid
    *
    * @param rid the value for user_role.rid
    *
    * @mbg.generated
    */
   public void setRid(Integer rid) {
       this.rid = rid;
   }
	
}
