package com.zzz.dao;

import java.util.List;

import com.zzz.entity.User;

public interface UserDao {
	List<User> findUserList();
	User selectUserByKey(User user);
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    int insertSelective(User user);

}
